#!/usr/bin/env python3
"""Reproduce the offline HTML named-reference table used by WebVTT imports.

Source: Python's standard-library html.entities.html5 (the WHATWG HTML named
character references, including legacy semicolonless aliases). Keep this data
in core.js so static/offline readers need no network fetch or extra dependency.
Run `python scripts/vtt_entities.py`, or `--check` to verify generated data.
"""
import argparse
import html.entities
import json
from pathlib import Path

PATH = Path(__file__).resolve().parents[1] / 'reader' / 'core.js'
START = ' // BEGIN GENERATED HTML NAMED REFERENCES\n'
END = ' // END GENERATED HTML NAMED REFERENCES\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    source = PATH.read_text()
    start, end = source.index(START), source.index(END) + len(END)
    table = json.dumps(html.entities.html5, ensure_ascii=True, sort_keys=True, separators=(',', ':'))
    generated = START + ' // Generated by scripts/vtt_entities.py from Python html.entities.html5.\n const VTT_ENTITIES = Object.freeze(' + table + ');\n' + END
    expected = source[:start] + generated + source[end:]
    if args.check:
        if source != expected:
            parser.exit(1, 'WebVTT entity data is stale. Run python scripts/vtt_entities.py\n')
    else:
        PATH.write_text(expected)


if __name__ == '__main__':
    main()
